#!/usr/bin/env python3

import pandas as pd
import json
from pprint import pprint

devices_data = [{'gnan02-3560sw-pr': [{'show_version': '{"version": "12.2(55)SE3", "rommon": '
                                        '"Bootstrap", "hostname": '
                                        '"gnan02-3560sw-pr", "uptime": "50 '
                                        'weeks, 18 hours, 40 minutes", '
                                        '"reload_reason": "power-on", '
                                        '"running_image": '
                                        '"/c3560e-universalk9-mz.122-55.SE3/c3560e-universalk9-mz.122-55.SE3.bin", '
                                        '"hardware": ["WS-C3560X-24"], '
                                        '"serial": ["FDO1536R1V9"], '
                                        '"config_register": "0xF", "mac": '
                                        '["CC:EF:48:DA:20:00"]}'},
                       {'show_clock': '{"time": "19:09:23.965", "timezone": '
                                      '"CL", "dayweek": "Thu", "month": "Mar", '
                                      '"day": "5", "year": "2020"}'}]},
 {'gnan12-2960sw-pr': [{'show_version': '{"version": "12.2(44)SE6", "rommon": '
                                        '"Bootstrap", "hostname": '
                                        '"gnan12-2960sw-pr", "uptime": "5 '
                                        'years, 14 weeks, 5 days, 8 hours, 37 '
                                        'minutes", "reload_reason": '
                                        '"power-on", "running_image": '
                                        '"c2960-lanbasek9-mz.122-44.SE6/c2960-lanbasek9-mz.122-44.SE6.bin", '
                                        '"hardware": ["WS-C2960-24PC-L"], '
                                        '"serial": ["FOC1421Z2QK"], '
                                        '"config_register": "0xF", "mac": '
                                        '["A8:B1:D4:06:11:80"]}'},
                       {'show_clock': '{"time": "19:09:18.557", "timezone": '
                                      '"CL", "dayweek": "Thu", "month": "Mar", '
                                      '"day": "5", "year": "2020"}'}]},
 {'RTR_ANGAMOS01': [{'show_version': '{"version": "15.4(3)M3", "rommon": '
                                     '"System", "hostname": "RTR_ANGAMOS01", '
                                     '"uptime": "49 weeks, 2 days, 6 hours, 30 '
                                     'minutes", "reload_reason": "power-on", '
                                     '"running_image": '
                                     '"c3900-universalk9-mz.SPA.154-3.M3.bin", '
                                     '"hardware": ["CISCO3925-CHASSIS"], '
                                     '"serial": ["FJC2028D155"], '
                                     '"config_register": "0x2102", "mac": []}'},
                    {'show_clock': '{"time": "19:09:38.401", "timezone": '
                                   '"Stgo", "dayweek": "Thu", "month": "Mar", '
                                   '"day": "5", "year": "2020"}'}]},
 {'sw-ang-Sala.Ctrl': [{'show_version': '{"version": "15.2(2)E6", "rommon": '
                                        '"Bootstrap", "hostname": '
                                        '"sw-ang-Sala.Ctrl", "uptime": "2 '
                                        'years, 15 weeks, 5 days, 9 hours, 21 '
                                        'minutes", "reload_reason": '
                                        '"power-on", "running_image": '
                                        '"/c2960-lanbasek9-mz.152-2.E6/c2960-lanbasek9-mz.152-2.E6.bin", '
                                        '"hardware": ["WS-C2960+24PC-L"], '
                                        '"serial": ["FOC2117Y2SF"], '
                                        '"config_register": "0xF", "mac": '
                                        '["00:A3:D1:E2:06:80"]}'},
                       {'show_clock': '{"time": "19:11:04.513", "timezone": '
                                      '"CL", "dayweek": "Thu", "month": "Mar", '
                                      '"day": "5", "year": "2020"}'}]},
 {'gnan10-3560sw-pr': [{'show_version': '{"version": "12.2(50)SE5", "rommon": '
                                        '"Bootstrap", "hostname": '
                                        '"gnan10-3560sw-pr", "uptime": "14 '
                                        'weeks, 2 hours, 48 minutes", '
                                        '"reload_reason": "power-on", '
                                        '"running_image": '
                                        '"/c3560-ipbasek9-mz.122-50.SE5/c3560-ipbasek9-mz.122-50.SE5.bin", '
                                        '"hardware": ["WS-C3560V2-24TS"], '
                                        '"serial": ["FDO1518X1TS"], '
                                        '"config_register": "0xF", "mac": '
                                        '["E8:BA:70:CB:B2:80"]}'},
                       {'show_clock': '{"time": "19:09:53.954", "timezone": '
                                      '"CL", "dayweek": "Thu", "month": "Mar", '
                                      '"day": "5", "year": "2020"}'}]}]

devices_data_1 = [{'CE-A': [{'show_interfaces': '[{"interface": "Ethernet0/0", "link_status": '
                               '"up", "protocol_status": "up (connected)", '
                               '"hardware_type": "AmdP2", "address": '
                               '"aabb.cc00.7100", "bia": "aabb.cc00.7100", '
                               '"description": "", "ip_address": "", "mtu": '
                               '"1500", "duplex": "Auto-duplex", "speed": '
                               '"Auto-speed", "bandwidth": "10000 Kbit", '
                               '"delay": "1000 usec", "encapsulation": "ARPA", '
                               '"last_input": "never", "last_output": '
                               '"00:00:01", "last_output_hang": "never", '
                               '"input_rate": "0", "output_rate": "0", '
                               '"input_packets": "0", "output_packets": '
                               '"87238", "input_errors": "0", "output_errors": '
                               '"0", "crc": "0"}, {"interface": "Ethernet0/1", '
                               '"link_status": "up", "protocol_status": "up '
                               '(connected)", "hardware_type": "Ethernet", '
                               '"address": "aabb.cc00.7110", "bia": '
                               '"aabb.cc00.7110", "description": "", '
                               '"ip_address": "10.2.10.10/24", "mtu": "1500", '
                               '"duplex": "Auto-duplex", "speed": '
                               '"Auto-speed", "bandwidth": "10000 Kbit", '
                               '"delay": "1000 usec", "encapsulation": "ARPA", '
                               '"last_input": "00:00:00", "last_output": '
                               '"00:00:00", "last_output_hang": "never", '
                               '"input_rate": "2000", "output_rate": "1000", '
                               '"input_packets": "29029", "output_packets": '
                               '"26302", "input_errors": "0", "output_errors": '
                               '"0", "crc": "0"}, {"interface": "Ethernet0/2", '
                               '"link_status": "administratively down", '
                               '"protocol_status": "down (disabled)", '
                               '"hardware_type": "AmdP2", "address": '
                               '"aabb.cc00.7120", "bia": "aabb.cc00.7120", '
                               '"description": "", "ip_address": "", "mtu": '
                               '"1500", "duplex": "Auto-duplex", "speed": '
                               '"Auto-speed", "bandwidth": "10000 Kbit", '
                               '"delay": "1000 usec", "encapsulation": "ARPA", '
                               '"last_input": "never", "last_output": "1d17h", '
                               '"last_output_hang": "never", "input_rate": '
                               '"0", "output_rate": "0", "input_packets": "0", '
                               '"output_packets": "2", "input_errors": "0", '
                               '"output_errors": "0", "crc": "0"}, '
                               '{"interface": "Ethernet0/3", "link_status": '
                               '"administratively down", "protocol_status": '
                               '"down (disabled)", "hardware_type": "AmdP2", '
                               '"address": "aabb.cc00.7130", "bia": '
                               '"aabb.cc00.7130", "description": "", '
                               '"ip_address": "", "mtu": "1500", "duplex": '
                               '"Auto-duplex", "speed": "Auto-speed", '
                               '"bandwidth": "10000 Kbit", "delay": "1000 '
                               'usec", "encapsulation": "ARPA", "last_input": '
                               '"never", "last_output": "1d17h", '
                               '"last_output_hang": "never", "input_rate": '
                               '"0", "output_rate": "0", "input_packets": "0", '
                               '"output_packets": "2", "input_errors": "0", '
                               '"output_errors": "0", "crc": "0"}, '
                               '{"interface": "Loopback0", "link_status": '
                               '"up", "protocol_status": "up", '
                               '"hardware_type": "Loopback", "address": "", '
                               '"bia": "", "description": "", "ip_address": '
                               '"10.10.10.10/32", "mtu": "1514", "duplex": "", '
                               '"speed": "", "bandwidth": "8000000 Kbit", '
                               '"delay": "5000 usec", "encapsulation": '
                               '"LOOPBACK", "last_input": "never", '
                               '"last_output": "never", "last_output_hang": '
                               '"never", "input_rate": "0", "output_rate": '
                               '"0", "input_packets": "0", "output_packets": '
                               '"0", "input_errors": "", "output_errors": "0", '
                               '"crc": ""}]'},
           {'show_interface_status': '[{"port": "Et0/0", "name": "", "status": '
                                     '"connected", "vlan": "1", "duplex": '
                                     '"auto", "speed": "auto", "type": '
                                     '"unknown"}, {"port": "Et0/1", "name": '
                                     '"", "status": "connected", "vlan": '
                                     '"routed", "duplex": "auto", "speed": '
                                     '"auto", "type": "unknown"}, {"port": '
                                     '"Et0/2", "name": "", "status": '
                                     '"disabled", "vlan": "1", "duplex": '
                                     '"auto", "speed": "auto", "type": '
                                     '"unknown"}, {"port": "Et0/3", "name": '
                                     '"", "status": "disabled", "vlan": "1", '
                                     '"duplex": "auto", "speed": "auto", '
                                     '"type": "unknown"}]'},
           {'show_version': '[{"version": "", "rommon": "Bootstrap", '
                            '"hostname": "CE-A", "uptime": "1 day, 17 hours, '
                            '26 minutes", "reload_reason": "Unknown reason", '
                            '"running_image": '
                            '"/opt/unetlab/addons/iol/bin/L2-ADVENTERPRISE-M-15.1-20140814.bin", '
                            '"hardware": [], "serial": ["67111025"], '
                            '"config_register": "0x0", "mac": []}]'},
           {'show_run': 'Building configuration...\n'
                        '\n'
                        'Current configuration : 1106 bytes\n'
                        '!\n'
                        'version 15.1\n'
                        'service timestamps debug datetime msec\n'
                        'service timestamps log datetime msec\n'
                        'no service password-encryption\n'
                        'service compress-config\n'
                        '!\n'
                        'hostname CE-A\n'
                        '!\n'
                        'boot-start-marker\n'
                        'boot-end-marker\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'username cisco privilege 15 secret 5 '
                        '$1$t00T$Y/5i3OevQWcXx0j/shIZE1\n'
                        'no aaa new-model\n'
                        'clock timezone EET 2 0\n'
                        '!\n'
                        'ip cef\n'
                        '!\n'
                        '!\n'
                        'no ip domain-lookup\n'
                        'ip domain-name cisco.com\n'
                        'no ipv6 cef\n'
                        'ipv6 multicast rpf use-bgp\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'spanning-tree mode pvst\n'
                        'spanning-tree extend system-id\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'vlan internal allocation policy ascending\n'
                        '!\n'
                        '! \n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'interface Loopback0\n'
                        ' ip address 10.10.10.10 255.255.255.255\n'
                        ' ip ospf network point-to-point\n'
                        '!\n'
                        'interface Ethernet0/0\n'
                        ' duplex auto\n'
                        '!\n'
                        'interface Ethernet0/1\n'
                        ' no switchport\n'
                        ' ip address 10.2.10.10 255.255.255.0\n'
                        ' duplex auto\n'
                        '!\n'
                        'interface Ethernet0/2\n'
                        ' shutdown\n'
                        ' duplex auto\n'
                        '!\n'
                        'interface Ethernet0/3\n'
                        ' shutdown\n'
                        ' duplex auto\n'
                        '!\n'
                        '!\n'
                        'no ip http server\n'
                        '!\n'
                        'ip route 0.0.0.0 0.0.0.0 10.2.10.2\n'
                        'ip route 10.6.20.0 255.255.255.0 10.1.10.1\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'control-plane\n'
                        '!\n'
                        '!\n'
                        'line con 0\n'
                        ' privilege level 15\n'
                        ' logging synchronous\n'
                        'line aux 0\n'
                        'line vty 0 4\n'
                        ' login local\n'
                        ' transport input ssh\n'
                        '!\n'
                        'end\n'}]},
 {'CE-B': [{'show_interfaces': '[{"interface": "Ethernet0/0", "link_status": '
                               '"up", "protocol_status": "up (connected)", '
                               '"hardware_type": "Ethernet", "address": '
                               '"aabb.cc00.8100", "bia": "aabb.cc00.8100", '
                               '"description": "", "ip_address": '
                               '"10.5.20.20/24", "mtu": "1500", "duplex": '
                               '"Auto-duplex", "speed": "Auto-speed", '
                               '"bandwidth": "10000 Kbit", "delay": "1000 '
                               'usec", "encapsulation": "ARPA", "last_input": '
                               '"00:00:00", "last_output": "00:00:00", '
                               '"last_output_hang": "never", "input_rate": '
                               '"1000", "output_rate": "1000", '
                               '"input_packets": "9816", "output_packets": '
                               '"43063", "input_errors": "0", "output_errors": '
                               '"0", "crc": "0"}, {"interface": "Ethernet0/1", '
                               '"link_status": "up", "protocol_status": "up '
                               '(connected)", "hardware_type": "AmdP2", '
                               '"address": "aabb.cc00.8110", "bia": '
                               '"aabb.cc00.8110", "description": "", '
                               '"ip_address": "", "mtu": "1500", "duplex": '
                               '"Auto-duplex", "speed": "Auto-speed", '
                               '"bandwidth": "10000 Kbit", "delay": "1000 '
                               'usec", "encapsulation": "ARPA", "last_input": '
                               '"never", "last_output": "00:00:00", '
                               '"last_output_hang": "never", "input_rate": '
                               '"0", "output_rate": "0", "input_packets": "0", '
                               '"output_packets": "885316", "input_errors": '
                               '"0", "output_errors": "0", "crc": "0"}, '
                               '{"interface": "Ethernet0/2", "link_status": '
                               '"administratively down", "protocol_status": '
                               '"down (disabled)", "hardware_type": "AmdP2", '
                               '"address": "aabb.cc00.8120", "bia": '
                               '"aabb.cc00.8120", "description": "", '
                               '"ip_address": "", "mtu": "1500", "duplex": '
                               '"Auto-duplex", "speed": "Auto-speed", '
                               '"bandwidth": "10000 Kbit", "delay": "1000 '
                               'usec", "encapsulation": "ARPA", "last_input": '
                               '"never", "last_output": "2w3d", '
                               '"last_output_hang": "never", "input_rate": '
                               '"0", "output_rate": "0", "input_packets": "0", '
                               '"output_packets": "2", "input_errors": "0", '
                               '"output_errors": "0", "crc": "0"}, '
                               '{"interface": "Ethernet0/3", "link_status": '
                               '"administratively down", "protocol_status": '
                               '"down (disabled)", "hardware_type": "AmdP2", '
                               '"address": "aabb.cc00.8130", "bia": '
                               '"aabb.cc00.8130", "description": "", '
                               '"ip_address": "", "mtu": "1500", "duplex": '
                               '"Auto-duplex", "speed": "Auto-speed", '
                               '"bandwidth": "10000 Kbit", "delay": "1000 '
                               'usec", "encapsulation": "ARPA", "last_input": '
                               '"never", "last_output": "2w3d", '
                               '"last_output_hang": "never", "input_rate": '
                               '"0", "output_rate": "0", "input_packets": "0", '
                               '"output_packets": "2", "input_errors": "0", '
                               '"output_errors": "0", "crc": "0"}, '
                               '{"interface": "Loopback0", "link_status": '
                               '"up", "protocol_status": "up", '
                               '"hardware_type": "Loopback", "address": "", '
                               '"bia": "", "description": "", "ip_address": '
                               '"20.20.20.20/32", "mtu": "1514", "duplex": "", '
                               '"speed": "", "bandwidth": "8000000 Kbit", '
                               '"delay": "5000 usec", "encapsulation": '
                               '"LOOPBACK", "last_input": "never", '
                               '"last_output": "never", "last_output_hang": '
                               '"never", "input_rate": "0", "output_rate": '
                               '"0", "input_packets": "0", "output_packets": '
                               '"0", "input_errors": "", "output_errors": "0", '
                               '"crc": ""}]'},
           {'show_interface_status': '[{"port": "Et0/0", "name": "", "status": '
                                     '"connected", "vlan": "routed", "duplex": '
                                     '"auto", "speed": "auto", "type": '
                                     '"unknown"}, {"port": "Et0/1", "name": '
                                     '"", "status": "connected", "vlan": "1", '
                                     '"duplex": "auto", "speed": "auto", '
                                     '"type": "unknown"}, {"port": "Et0/2", '
                                     '"name": "", "status": "disabled", '
                                     '"vlan": "1", "duplex": "auto", "speed": '
                                     '"auto", "type": "unknown"}, {"port": '
                                     '"Et0/3", "name": "", "status": '
                                     '"disabled", "vlan": "1", "duplex": '
                                     '"auto", "speed": "auto", "type": '
                                     '"unknown"}]'},
           {'show_version': '[{"version": "", "rommon": "Bootstrap", '
                            '"hostname": "CE-B", "uptime": "2 weeks, 3 days, '
                            '12 hours, 32 minutes", "reload_reason": "Unknown '
                            'reason", "running_image": '
                            '"/opt/unetlab/addons/iol/bin/L2-ADVENTERPRISE-M-15.1-20140814.bin", '
                            '"hardware": [], "serial": ["67111041"], '
                            '"config_register": "0x0", "mac": []}]'},
           {'show_run': 'Building configuration...\n'
                        '\n'
                        'Current configuration : 1153 bytes\n'
                        '!\n'
                        '! Last configuration change at 21:02:09 EET Wed Feb '
                        '19 2020\n'
                        '!\n'
                        'version 15.1\n'
                        'service timestamps debug datetime msec\n'
                        'service timestamps log datetime msec\n'
                        'no service password-encryption\n'
                        'service compress-config\n'
                        '!\n'
                        'hostname CE-B\n'
                        '!\n'
                        'boot-start-marker\n'
                        'boot-end-marker\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'username cisco privilege 15 secret 5 '
                        '$1$fQ/5$mCasfUzAs4VFmyDHPbhhv1\n'
                        'no aaa new-model\n'
                        'clock timezone EET 2 0\n'
                        '!\n'
                        'ip cef\n'
                        '!\n'
                        '!\n'
                        'no ip domain-lookup\n'
                        'ip domain-name cisco.com\n'
                        'no ipv6 cef\n'
                        'ipv6 multicast rpf use-bgp\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'spanning-tree mode pvst\n'
                        'spanning-tree extend system-id\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'vlan internal allocation policy ascending\n'
                        '!\n'
                        'ip ssh version 2\n'
                        '! \n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'interface Loopback0\n'
                        ' ip address 20.20.20.20 255.255.255.255\n'
                        '!\n'
                        'interface Ethernet0/0\n'
                        ' no switchport\n'
                        ' ip address 10.5.20.20 255.255.255.0\n'
                        ' duplex auto\n'
                        '!\n'
                        'interface Ethernet0/1\n'
                        ' duplex auto\n'
                        '!\n'
                        'interface Ethernet0/2\n'
                        ' shutdown\n'
                        ' duplex auto\n'
                        '!\n'
                        'interface Ethernet0/3\n'
                        ' shutdown\n'
                        ' duplex auto\n'
                        '!\n'
                        '!\n'
                        'no ip http server\n'
                        '!\n'
                        'ip route 0.0.0.0 0.0.0.0 10.5.20.5\n'
                        'ip route 10.1.10.0 255.255.255.0 10.6.20.6\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        '!\n'
                        'control-plane\n'
                        '!\n'
                        '!\n'
                        'line con 0\n'
                        ' privilege level 15\n'
                        ' logging synchronous\n'
                        'line aux 0\n'
                        'line vty 0 4\n'
                        ' login local\n'
                        ' transport input ssh\n'
                        '!\n'
                        'end\n'}]}]

<<<<<<< HEAD
result = {
    "device_name": []
}


for device in devices_data:
    for hostname, device_data in device.items():
        result["device_name"].append(hostname)
        for data in device_data:
            for command, output in data.items():
                for key, value in json.loads(output).items():
                    try:
                        result[key].append(value)
                    except KeyError:
                        result[key] = []
                        result[key].append(value)


df = pd.DataFrame(result)
print(df)

=======
def dataframe(data):
    for device in data:
        for hostname, device_data in device.items():
            for data in device_data:
                for output in data.values():
                    result = {
                        "device_name": []
                    }
                    try:        
                        for item in json.loads(output):
                            result["device_name"].append(hostname)
                            for key, value in item.items():
                                try:
                                    result[key].append(value)
                                except KeyError:
                                    result[key] = []
                                    result[key].append(value)
                        df = pd.DataFrame(result)
                        print(df)
                    except:
                        continue
>>>>>>> testing
